"use client";

import { useState } from "react";
import { Copy, Check } from "lucide-react";

type Impact = "critical" | "serious" | "moderate" | "minor";

type ReportData = {
  url: string;
  score: number;
  issue_count: number;
  summary: Record<Impact, number>;
  issues: Array<{
    id: string;
    impact: Impact;
    help: string;
    description: string;
  }>;
};

const impactOrder: Record<Impact, number> = {
  critical: 0,
  serious: 1,
  moderate: 2,
  minor: 3
};

function getDomain(targetUrl: string) {
  try {
    return new URL(targetUrl).hostname.replace(/^www\./, "");
  } catch {
    return targetUrl;
  }
}

function getReportStatusLabel(report: ReportData) {
  if (report.summary.critical > 0) return "Blocked";
  if (report.summary.serious > 0) return "Needs fixes";
  if (report.score < 90) return "Needs fixes";
  return "Ready";
}

function generateClientSummary(report: ReportData) {
  const domain = getDomain(report.url);
  const status = getReportStatusLabel(report);
  const issueCountText = `${report.issue_count} issue group${report.issue_count === 1 ? "" : "s"}`;
  const topIssue = [...report.issues].sort((a, b) => impactOrder[a.impact] - impactOrder[b.impact])[0];

  let summary = `Pre-handoff accessibility check for ${domain}\n`;
  summary += `Status: ${status}\n`;
  summary += `Access score: ${report.score}/100\n`;
  summary += `${status === "Blocked" || status === "Needs fixes" ? issueCountText + " found" : "No high-risk issues found"}\n`;

  if (topIssue) {
    summary += `\nTop fix: ${topIssue.help}`;
  }

  summary += `\n\nGenerated by AccessPing — automated first pass, not a full audit.`;
  return summary;
}

interface SharedCopyableSummaryProps {
  report: ReportData;
}

export default function SharedCopyableSummary({ report }: SharedCopyableSummaryProps) {
  const [copied, setCopied] = useState(false);
  const summaryText = generateClientSummary(report);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = summaryText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <section className="copyableSummary">
      <div className="copyableSummaryHeader">
        <span>Client summary</span>
        <button type="button" onClick={handleCopy} className="copyButton">
          {copied ? (
            <>
              <Check size={15} />
              Copied
            </>
          ) : (
            <>
              <Copy size={15} />
              Copy
            </>
          )}
        </button>
      </div>
      <pre className="copyableSummaryText">{summaryText}</pre>
    </section>
  );
}